// <auto-generated />
using System;
using Doublelives.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Doublelives.Migrations.Migrations
{
    [DbContext(typeof(DlAdminDbContext))]
    [Migration("20200422101628_optimized-struct")]
    partial class optimizedstruct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsArticle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnName("author")
                        .HasColumnType("text(64)");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdChannel")
                        .HasColumnName("id_channel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Img")
                        .HasColumnName("img")
                        .HasColumnType("text(64)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text(128)");

                    b.HasKey("Id");

                    b.ToTable("cms_article");
                });

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsBanner", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdFile")
                        .HasColumnName("id_file")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text(64)");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text(32)");

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("text(128)");

                    b.HasKey("Id");

                    b.ToTable("cms_banner");
                });

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsChannel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("text(64)");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text(64)");

                    b.HasKey("Id");

                    b.ToTable("cms_channel");
                });

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsContacts", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text(32)");

                    b.Property<string>("Mobile")
                        .HasColumnName("mobile")
                        .HasColumnType("text(64)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnName("remark")
                        .HasColumnType("text(128)");

                    b.Property<string>("UserName")
                        .HasColumnName("user_name")
                        .HasColumnType("text(64)");

                    b.HasKey("Id");

                    b.ToTable("cms_contacts");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.Message", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Receiver")
                        .HasColumnName("receiver")
                        .HasColumnType("text(64)");

                    b.Property<string>("State")
                        .HasColumnName("state")
                        .HasColumnType("text(32)");

                    b.Property<string>("TplCode")
                        .HasColumnName("tpl_code")
                        .HasColumnType("text(32)");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text(32)");

                    b.HasKey("Id");

                    b.ToTable("message");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.MessageSender", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnName("class_name")
                        .HasColumnType("text(64)");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text(64)");

                    b.Property<string>("TplCode")
                        .HasColumnName("tpl_code")
                        .HasColumnType("text(64)");

                    b.HasKey("Id");

                    b.ToTable("message_sender");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("text(32)");

                    b.Property<string>("Cond")
                        .HasColumnName("cond")
                        .HasColumnType("text(32)");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdMessageSender")
                        .HasColumnName("id_message_sender")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text(64)");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text(32)");

                    b.HasKey("Id");

                    b.HasIndex("IdMessageSender")
                        .HasName("FK942sadqk5x9kbrwil0psyek3n");

                    b.ToTable("message_template");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysCfg", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CfgDesc")
                        .HasColumnName("cfg_desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CfgName")
                        .HasColumnName("cfg_name")
                        .HasColumnType("text(256)");

                    b.Property<string>("CfgValue")
                        .HasColumnName("cfg_value")
                        .HasColumnType("text(512)");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("sys_cfg");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysDept", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullname")
                        .HasColumnName("fullname")
                        .HasColumnType("text(255)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Num")
                        .HasColumnName("num")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pid")
                        .HasColumnName("pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pids")
                        .HasColumnName("pids")
                        .HasColumnType("text(255)");

                    b.Property<string>("Simplename")
                        .HasColumnName("simplename")
                        .HasColumnType("text(255)");

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("text(255)");

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_dept");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysDict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text(255)");

                    b.Property<string>("Num")
                        .HasColumnName("num")
                        .HasColumnType("text(255)");

                    b.Property<int?>("Pid")
                        .HasColumnName("pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("text(255)");

                    b.HasKey("Id");

                    b.ToTable("sys_dict");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysFileInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasColumnName("original_file_name")
                        .HasColumnType("text(255)");

                    b.Property<string>("RealFileName")
                        .HasColumnName("real_file_name")
                        .HasColumnType("text(255)");

                    b.HasKey("Id");

                    b.ToTable("sys_file_info");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysLoginLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnName("ip")
                        .HasColumnType("text(255)");

                    b.Property<string>("Logname")
                        .HasColumnName("logname")
                        .HasColumnType("text(255)");

                    b.Property<string>("Message")
                        .HasColumnName("message")
                        .HasColumnType("text(255)");

                    b.Property<string>("Succeed")
                        .HasColumnName("succeed")
                        .HasColumnType("text(255)");

                    b.Property<int?>("Userid")
                        .HasColumnName("userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_login_log");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("text(32)");

                    b.Property<string>("Component")
                        .HasColumnName("component")
                        .HasColumnType("text(64)");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnName("hidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnName("icon")
                        .HasColumnType("text(32)");

                    b.Property<bool>("Ismenu")
                        .HasColumnName("ismenu")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Isopen")
                        .HasColumnName("isopen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Levels")
                        .HasColumnName("levels")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text(64)");

                    b.Property<int>("Num")
                        .HasColumnName("num")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pcode")
                        .IsRequired()
                        .HasColumnName("pcode")
                        .HasColumnType("text(64)");

                    b.Property<string>("Pcodes")
                        .HasColumnName("pcodes")
                        .HasColumnType("text(128)");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("text(32)");

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("text(32)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("UK_s37unj3gh67ujhk83lqva8i1t");

                    b.ToTable("sys_menu");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysNotice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("text(255)");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text(255)");

                    b.Property<int?>("Type")
                        .HasColumnName("type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_notice");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysOperationLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classname")
                        .HasColumnName("classname")
                        .HasColumnType("text(255)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logname")
                        .HasColumnName("logname")
                        .HasColumnType("text(255)");

                    b.Property<string>("Logtype")
                        .HasColumnName("logtype")
                        .HasColumnType("text(255)");

                    b.Property<string>("Message")
                        .HasColumnName("message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnName("method")
                        .HasColumnType("text(255)");

                    b.Property<string>("Succeed")
                        .HasColumnName("succeed")
                        .HasColumnType("text(255)");

                    b.Property<int?>("Userid")
                        .HasColumnName("userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_operation_log");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysRelation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Menuid")
                        .HasColumnName("menuid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Roleid")
                        .HasColumnName("roleid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_relation");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Deptid")
                        .HasColumnName("deptid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text(255)");

                    b.Property<int?>("Num")
                        .HasColumnName("num")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pid")
                        .HasColumnName("pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("text(255)");

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_role");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysTask", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Concurrent")
                        .HasColumnName("concurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cron")
                        .HasColumnName("cron")
                        .HasColumnType("text(50)");

                    b.Property<string>("Data")
                        .HasColumnName("data")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Disabled")
                        .HasColumnName("disabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecAt")
                        .HasColumnName("exec_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecResult")
                        .HasColumnName("exec_result")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobClass")
                        .HasColumnName("job_class")
                        .HasColumnType("text(255)");

                    b.Property<string>("JobGroup")
                        .HasColumnName("job_group")
                        .HasColumnType("text(50)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text(50)");

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasColumnType("text(255)");

                    b.HasKey("Id");

                    b.ToTable("sys_task");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecAt")
                        .HasColumnName("exec_at")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ExecSuccess")
                        .HasColumnName("exec_success")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTask")
                        .HasColumnName("id_task")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobException")
                        .HasColumnName("job_exception")
                        .HasColumnType("text(500)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text(50)");

                    b.HasKey("Id");

                    b.ToTable("sys_task_log");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .HasColumnName("account")
                        .HasColumnType("text(32)");

                    b.Property<string>("Avatar")
                        .HasColumnName("avatar")
                        .HasColumnType("text(255)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnName("birthday")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Deptid")
                        .HasColumnName("deptid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text(64)");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text(64)");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text(64)");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("text(16)");

                    b.Property<string>("Roleid")
                        .HasColumnName("roleid")
                        .HasColumnType("text(128)");

                    b.Property<string>("Salt")
                        .HasColumnName("salt")
                        .HasColumnType("text(16)");

                    b.Property<int?>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.MessageTemplate", b =>
                {
                    b.HasOne("Doublelives.Domain.Messages.MessageSender", "IdMessageSenderNavigation")
                        .WithMany("MessageTemplate")
                        .HasForeignKey("IdMessageSender")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
