// <auto-generated />
using System;
using Doublelives.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Doublelives.Migrations.Migrations
{
    [DbContext(typeof(DlAdminDbContext))]
    [Migration("20200427193723_init_pgsql2")]
    partial class init_pgsql2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Author")
                        .HasColumnName("author")
                        .HasColumnType("character varying(64)")
                        .HasComment("作者")
                        .HasMaxLength(64);

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("character varying(65535)")
                        .HasComment("内容")
                        .HasMaxLength(65535);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int>("IdChannel")
                        .HasColumnName("id_channel")
                        .HasColumnType("integer")
                        .HasComment("栏目id");

                    b.Property<string>("Img")
                        .HasColumnName("img")
                        .HasColumnType("character varying(64)")
                        .HasComment("文章题图id")
                        .HasMaxLength(64);

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("character varying(128)")
                        .HasComment("文章标题")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("cms_article");

                    b.HasComment("文章");
                });

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("IdFile")
                        .HasColumnName("id_file")
                        .HasColumnType("integer")
                        .HasComment("banner图id");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("character varying(64)")
                        .HasComment("标题")
                        .HasMaxLength(64);

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("character varying(32)")
                        .HasComment("类型")
                        .HasMaxLength(32);

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("character varying(128)")
                        .HasComment("点击banner跳转到url")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("cms_banner");
                });

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("character varying(64)")
                        .HasComment("编码")
                        .HasMaxLength(64);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(64)")
                        .HasComment("名称")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("cms_channel");

                    b.HasComment("文章栏目");
                });

            modelBuilder.Entity("Doublelives.Domain.Cms.CmsContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("character varying(32)")
                        .HasComment("邮箱")
                        .HasMaxLength(32);

                    b.Property<string>("Mobile")
                        .HasColumnName("mobile")
                        .HasColumnType("character varying(64)")
                        .HasComment("联系电话")
                        .HasMaxLength(64);

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Remark")
                        .HasColumnName("remark")
                        .HasColumnType("character varying(128)")
                        .HasComment("备注")
                        .HasMaxLength(128);

                    b.Property<string>("UserName")
                        .HasColumnName("user_name")
                        .HasColumnType("character varying(64)")
                        .HasComment("邀约人名称")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("cms_contacts");

                    b.HasComment("邀约信息");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("character varying(65535)")
                        .HasComment("消息内容")
                        .HasMaxLength(65535);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Receiver")
                        .HasColumnName("receiver")
                        .HasColumnType("character varying(64)")
                        .HasComment("接收者")
                        .HasMaxLength(64);

                    b.Property<int>("State")
                        .HasColumnName("state")
                        .HasColumnType("integer")
                        .HasComment("消息类型,0:初始,1:成功,2:失败");

                    b.Property<string>("TplCode")
                        .HasColumnName("tpl_code")
                        .HasColumnType("character varying(32)")
                        .HasComment("模板编码")
                        .HasMaxLength(32);

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer")
                        .HasComment("消息类型,0:短信,1:邮件");

                    b.HasKey("Id");

                    b.ToTable("message");

                    b.HasComment("历史消息");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.MessageSender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClassName")
                        .HasColumnName("class_name")
                        .HasColumnType("character varying(64)")
                        .HasComment("发送类")
                        .HasMaxLength(64);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(64)")
                        .HasComment("名称")
                        .HasMaxLength(64);

                    b.Property<string>("TplCode")
                        .HasColumnName("tpl_code")
                        .HasColumnType("character varying(64)")
                        .HasComment("运营商模板编号")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("message_sender");

                    b.HasComment("消息发送者");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("character varying(32)")
                        .HasComment("编号")
                        .HasMaxLength(32);

                    b.Property<string>("Cond")
                        .HasColumnName("cond")
                        .HasColumnType("character varying(32)")
                        .HasComment("发送条件")
                        .HasMaxLength(32);

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("character varying(65535)")
                        .HasComment("内容")
                        .HasMaxLength(65535);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int>("IdMessageSender")
                        .HasColumnName("id_message_sender")
                        .HasColumnType("integer")
                        .HasComment("发送者id");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("character varying(64)")
                        .HasComment("标题")
                        .HasMaxLength(64);

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer")
                        .HasComment("消息类型,0:短信,1:邮件");

                    b.HasKey("Id");

                    b.HasIndex("IdMessageSender")
                        .HasName("FK942sadqk5x9kbrwil0psyek3n");

                    b.ToTable("message_template");

                    b.HasComment("消息模板");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysCfg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CfgDesc")
                        .HasColumnName("cfg_desc")
                        .HasColumnType("character varying(65535)")
                        .HasComment("备注")
                        .HasMaxLength(65535);

                    b.Property<string>("CfgName")
                        .HasColumnName("cfg_name")
                        .HasColumnType("character varying(256)")
                        .HasComment("参数名")
                        .HasMaxLength(256);

                    b.Property<string>("CfgValue")
                        .HasColumnName("cfg_value")
                        .HasColumnType("character varying(512)")
                        .HasComment("参数值")
                        .HasMaxLength(512);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.HasKey("Id");

                    b.ToTable("sys_cfg");

                    b.HasComment("系统参数");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysDept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Fullname")
                        .HasColumnName("fullname")
                        .HasColumnType("character varying(255)")
                        .HasComment("全称")
                        .HasMaxLength(255);

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<int?>("Num")
                        .HasColumnName("num")
                        .HasColumnType("integer");

                    b.Property<int?>("Pid")
                        .HasColumnName("pid")
                        .HasColumnType("integer");

                    b.Property<string>("Pids")
                        .HasColumnName("pids")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Simplename")
                        .HasColumnName("simplename")
                        .HasColumnType("character varying(255)")
                        .HasComment("简称")
                        .HasMaxLength(255);

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sys_dept");

                    b.HasComment("部门");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysDict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Num")
                        .HasColumnName("num")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Pid")
                        .HasColumnName("pid")
                        .HasColumnType("integer");

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("sys_dict");

                    b.HasComment("字典");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysFileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("OriginalFileName")
                        .HasColumnName("original_file_name")
                        .HasColumnType("character varying(255)")
                        .HasComment("实际名称")
                        .HasMaxLength(255);

                    b.Property<string>("RealFileName")
                        .HasColumnName("real_file_name")
                        .HasColumnType("character varying(255)")
                        .HasComment("显示名称")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("sys_file_info");

                    b.HasComment("文件信息");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysLoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Ip")
                        .HasColumnName("ip")
                        .HasColumnType("character varying(255)")
                        .HasComment("登录ip")
                        .HasMaxLength(255);

                    b.Property<string>("Logname")
                        .HasColumnName("logname")
                        .HasColumnType("character varying(255)")
                        .HasComment("登陆者姓名")
                        .HasMaxLength(255);

                    b.Property<string>("Message")
                        .HasColumnName("message")
                        .HasColumnType("character varying(255)")
                        .HasComment("消息")
                        .HasMaxLength(255);

                    b.Property<bool>("Succeed")
                        .HasColumnName("succeed")
                        .HasColumnType("boolean")
                        .HasComment("是否成功");

                    b.Property<int?>("Userid")
                        .HasColumnName("userid")
                        .HasColumnType("integer")
                        .HasComment("用户id");

                    b.HasKey("Id");

                    b.ToTable("sys_login_log");

                    b.HasComment("登录日志");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("character varying(32)")
                        .HasComment("菜单编号")
                        .HasMaxLength(32);

                    b.Property<string>("Component")
                        .HasColumnName("component")
                        .HasColumnType("character varying(64)")
                        .HasComment("菜单对应的组件")
                        .HasMaxLength(64);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<bool>("Hidden")
                        .HasColumnName("hidden")
                        .HasColumnType("boolean")
                        .HasComment("是否隐藏");

                    b.Property<string>("Icon")
                        .HasColumnName("icon")
                        .HasColumnType("character varying(32)")
                        .HasComment("图标")
                        .HasMaxLength(32);

                    b.Property<bool>("Ismenu")
                        .HasColumnName("ismenu")
                        .HasColumnType("boolean")
                        .HasComment("是否是菜单1:菜单,0:按钮");

                    b.Property<bool?>("Isopen")
                        .HasColumnName("isopen")
                        .HasColumnType("boolean")
                        .HasComment("是否默认打开1:是,0:否");

                    b.Property<int>("Levels")
                        .HasColumnName("levels")
                        .HasColumnType("integer")
                        .HasComment("层级");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(64)")
                        .HasComment("名称")
                        .HasMaxLength(64);

                    b.Property<int>("Num")
                        .HasColumnName("num")
                        .HasColumnType("integer")
                        .HasComment("顺序");

                    b.Property<string>("Pcode")
                        .IsRequired()
                        .HasColumnName("pcode")
                        .HasColumnType("character varying(64)")
                        .HasComment("父菜单编号")
                        .HasMaxLength(64);

                    b.Property<string>("Pcodes")
                        .HasColumnName("pcodes")
                        .HasColumnType("character varying(128)")
                        .HasComment("递归父级菜单编号")
                        .HasMaxLength(128);

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("integer")
                        .HasComment("状态1:启用,0:禁用");

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("character varying(32)")
                        .HasComment("鼠标悬停提示信息")
                        .HasMaxLength(32);

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("character varying(32)")
                        .HasComment("链接")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasName("UK_s37unj3gh67ujhk83lqva8i1t");

                    b.ToTable("sys_menu");

                    b.HasComment("菜单");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysNotice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("character varying(255)")
                        .HasComment("内容")
                        .HasMaxLength(255);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("character varying(255)")
                        .HasComment("标题")
                        .HasMaxLength(255);

                    b.Property<int?>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sys_notice");

                    b.HasComment("欢迎弹窗");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysOperationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Classname")
                        .HasColumnName("classname")
                        .HasColumnType("character varying(255)")
                        .HasComment("操作类名")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Logname")
                        .HasColumnName("logname")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Logtype")
                        .HasColumnName("logtype")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Message")
                        .HasColumnName("message")
                        .HasColumnType("text")
                        .HasComment("详细信息");

                    b.Property<string>("Method")
                        .HasColumnName("method")
                        .HasColumnType("character varying(255)")
                        .HasComment("方法名")
                        .HasMaxLength(255);

                    b.Property<bool>("Succeed")
                        .HasColumnName("succeed")
                        .HasColumnType("boolean");

                    b.Property<int?>("Userid")
                        .HasColumnName("userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sys_operation_log");

                    b.HasComment("操作日志");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Menuid")
                        .HasColumnName("menuid")
                        .HasColumnType("integer");

                    b.Property<int>("Roleid")
                        .HasColumnName("roleid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sys_relation");

                    b.HasComment("角色和菜单的多对多中间表");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("Deptid")
                        .HasColumnName("deptid")
                        .HasColumnType("integer")
                        .HasComment("部门id");

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasComment("角色名")
                        .HasMaxLength(255);

                    b.Property<int?>("Num")
                        .HasColumnName("num")
                        .HasColumnType("integer")
                        .HasComment("用于排序");

                    b.Property<int?>("Pid")
                        .HasColumnName("pid")
                        .HasColumnType("integer");

                    b.Property<string>("Tips")
                        .HasColumnName("tips")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sys_role");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("Concurrent")
                        .HasColumnName("concurrent")
                        .HasColumnType("boolean")
                        .HasComment("是否允许并发");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Cron")
                        .HasColumnName("cron")
                        .HasColumnType("character varying(50)")
                        .HasComment("corn表达式")
                        .HasMaxLength(50);

                    b.Property<string>("Data")
                        .HasColumnName("data")
                        .HasColumnType("character varying(65535)")
                        .HasComment("执行参数")
                        .HasMaxLength(65535);

                    b.Property<bool?>("Disabled")
                        .HasColumnName("disabled")
                        .HasColumnType("boolean")
                        .HasComment("是否禁用");

                    b.Property<DateTime?>("ExecAt")
                        .HasColumnName("exec_at")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("上次执行时间");

                    b.Property<string>("ExecResult")
                        .HasColumnName("exec_result")
                        .HasColumnType("character varying(65535)")
                        .HasComment("执行结果")
                        .HasMaxLength(65535);

                    b.Property<string>("JobClass")
                        .HasColumnName("job_class")
                        .HasColumnType("character varying(255)")
                        .HasComment("执行类")
                        .HasMaxLength(255);

                    b.Property<string>("JobGroup")
                        .HasColumnName("job_group")
                        .HasColumnType("character varying(50)")
                        .HasComment("任务组")
                        .HasMaxLength(50);

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasComment("任务名")
                        .HasMaxLength(50);

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasColumnType("character varying(50)")
                        .HasComment("任务说明")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("sys_task");

                    b.HasComment("定时任务");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("ExecAt")
                        .HasColumnName("exec_at")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("执行时间");

                    b.Property<bool?>("ExecSuccess")
                        .HasColumnName("exec_success")
                        .HasColumnType("boolean")
                        .HasComment("是否执行成功");

                    b.Property<int?>("IdTask")
                        .HasColumnName("id_task")
                        .HasColumnType("integer")
                        .HasComment("任务id");

                    b.Property<string>("JobException")
                        .HasColumnName("job_exception")
                        .HasColumnType("character varying(500)")
                        .HasComment("异常日志")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(50)")
                        .HasComment("任务名")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("sys_task_log");

                    b.HasComment("定时任务日志");
                });

            modelBuilder.Entity("Doublelives.Domain.Sys.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasComment("主键")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Account")
                        .HasColumnName("account")
                        .HasColumnType("character varying(32)")
                        .HasComment("登录账户")
                        .HasMaxLength(32);

                    b.Property<string>("Avatar")
                        .HasColumnName("avatar")
                        .HasColumnType("character varying(255)")
                        .HasComment("头像")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnName("birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("生日");

                    b.Property<int?>("CreateBy")
                        .HasColumnName("create_by")
                        .HasColumnType("integer")
                        .HasComment("创建者");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("创建时间");

                    b.Property<int?>("Deptid")
                        .HasColumnName("deptid")
                        .HasColumnType("integer")
                        .HasComment("部门id");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("character varying(64)")
                        .HasComment("电子邮箱")
                        .HasMaxLength(64);

                    b.Property<int?>("ModifyBy")
                        .HasColumnName("modify_by")
                        .HasColumnType("integer")
                        .HasComment("最后修改者");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("modify_time")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("最后修改时间");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(64)")
                        .HasComment("显示的姓名")
                        .HasMaxLength(64);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("character varying(64)")
                        .HasComment("加密后的密码")
                        .HasMaxLength(64);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("character varying(16)")
                        .HasComment("联系电话")
                        .HasMaxLength(16);

                    b.Property<string>("Roleid")
                        .HasColumnName("roleid")
                        .HasColumnType("character varying(128)")
                        .HasComment("角色id列表，以逗号分隔")
                        .HasMaxLength(128);

                    b.Property<string>("Salt")
                        .HasColumnName("salt")
                        .HasColumnType("character varying(16)")
                        .HasComment("密码盐")
                        .HasMaxLength(16);

                    b.Property<int?>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("integer")
                        .HasComment("性别");

                    b.Property<int?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("integer")
                        .HasComment("账户状态");

                    b.Property<int?>("Version")
                        .HasColumnName("version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sys_user");

                    b.HasComment("用户表");
                });

            modelBuilder.Entity("Doublelives.Domain.Messages.MessageTemplate", b =>
                {
                    b.HasOne("Doublelives.Domain.Messages.MessageSender", "IdMessageSenderNavigation")
                        .WithMany("MessageTemplate")
                        .HasForeignKey("IdMessageSender")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
