$settings = get-content "Doublelives.Api/appsettings.json" | convertfrom-json;
$settings.tencentCos.appId = $env:AppId;
$settings.tencentCos.secretId = $env:SecretId;
$settings.tencentCos.secretKey = $env:SecretKey;
$settings.tencentCos.bucket = $env:Bucket;
$settings.tencentCos.region = $env:Region;
$settings.tencentCos.durationSecond = $env:DurationSecond;
$settings.tencentCos.baseUrl = $env:BaseUrl;
$settings.sentryClientKey = $env:SentryClientKey;
$settings.ConnectionStrings.dl = $env:Album;
$settings.jwt.key = $env:JwtKey;
$settings.jwt.issuer = $env:Issuer;
$settings.jwt.audience = $env:Audience;
$settings.jwt.expireMinutes = $env:ExpireMinutes;
$settings.cache.enable = $env:cache_enable;
$settings.cache.redisconn = $env:cache_redisconn;
$settings.cache.defaultExpireMinutes = $env:cache_defaultExpireMinutes;
set-content "Doublelives.Api/appsettings.json" ($settings | convertto-json);