pool:
  vmImage: "ubuntu-latest"

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - dl-api-csharp/*
      - .gitignore
      - README.md

variables:
  - group: docker_hub_username_pwd # 引用变量组

  - name: applicationName
    value: dl-vue-admin

  - name: imageName
    value: "$(dockerid)/$(applicationName):latest"

  - name: workingDirectory
    value: $(applicationName)

steps:
  - script: |
      npm install
      npm run build:prod
    workingDirectory: $(workingDirectory)
    displayName: "npm install"

  - script: |
      npm run build:prod
    workingDirectory: $(workingDirectory)
    displayName: "npm build for prod"

  - task: CopyFiles@2
    inputs:
      SourceFolder: dl-vue-admin/dist
      TargetFolder: '$(build.artifactstagingdirectory)/dist'
    displayName: 'Copy dist'

  - task: CopyFiles@2
    inputs:
      SourceFolder: dl-vue-admin
      Contents: Dockerfile
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy Dockerfile'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    displayName: 'Publish temp files'

  # - script: docker build -f Dockerfile -t $(imageName) .
  #   workingDirectory: $(workingDirectory)
  #   displayName: "Docker build"

  # - script: |
  #     docker login -u $(dockerid) -p $(password)
  #     docker push $(imageName)
  #   displayName: "Push docker image"
