pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - dl-api-csharp/*
      - .gitignore
      - README.md

variables:
  applicationName: dl-vue-admin
  imageName: '$(dockerid)/$(applicationName):latest'
  workingDirectory: $(applicationName)

steps:
  - script: |
      npm install
      npm run build:prod
    workingDirectory: $(workingDirectory)
    displayName: 'npm install and build'

  - script: docker build -f Dockerfile -t $(imageName) .
    workingDirectory: $(workingDirectory)
    displayName: 'Docker build'

  - script: |
      docker login -u $(dockerid) -p $(password)
      docker push $(imageName)
    displayName: 'Push docker image'