pool:
  vmImage: "ubuntu-latest"

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - dl-api-csharp/*
      - .gitignore
      - README.md

variables:
  - group: docker_hub_username_pwd # 引用变量组

  - name: applicationName
    value: dl-vue-admin

  - name: workingDirectory
    value: $(applicationName)

steps:
  - script: |
      npm install
      npm run build:prod
    workingDirectory: $(workingDirectory)
    displayName: "npm install"

  - script: |
      npm run build:prod
    workingDirectory: $(workingDirectory)
    displayName: "npm build for prod"

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(workingDirectory)/dist
      TargetFolder: '$(build.artifactstagingdirectory)/dist'
    displayName: 'Copy dist'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(workingDirectory)/deploy
      TargetFolder: '$(build.artifactstagingdirectory)/deploy'
    displayName: 'Copy deploy/server.js'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(workingDirectory)
      Contents: Dockerfile
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy Dockerfile'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(workingDirectory)
      Contents: docker-compose.yml
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy docker-compose.yml'

  - task: CopyFiles@2
    inputs:
      Contents: deploy.sh
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy deploy.sh'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    displayName: 'Publish temp files'
